base:
  command: /bin/true
  build: .

console:
  image: registrator_base
  entrypoint: /bin/bash
  hostname: registrator
  domainname: docker.local
  ports:
    - "5000:5000/udp"
    - "5555:5555/udp"
  volumes:
    - ./src:/usr/src/app/src
    - ./config:/usr/src/app/config
    - ./rebar.config:/usr/src/app/rebar.config
    - /var/run/docker.sock:/tmp/docker.sock
  volumes_from:
    - base
