base:
  command: /bin/true
  build: .

console:
  image: registrator_base
  entrypoint: /bin/bash
  hostname: registrator
  domainname: docker.local
  ports:
    - "5000/udp"
    - "5555/udp"
  volumes:
    - /var/run/docker.sock:/tmp/docker.sock
  volumes_from:
    - base
